server:
    port: 8089

spring:
    application:
        name: payment-service
    datasource:
        url: jdbc:mysql://${DB_HOST:localhost}:3306/codesync_payment_db?createDatabaseIfNotExist=true
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect

# Razorpay Specific Config
razorpay:
    key:
        id: ${RAZORPAY_KEY_ID}
        secret: ${RAZORPAY_KEY_SECRET}

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

# Monitoring (Spring Boot Admin)
management:
    endpoints:
        web:
            exposure:
                include: "*"
