server:
  port: 8085

spring:
  application:
    name: execution-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/codesync_execution_db?createDatabaseIfNotExist=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}

  boot:
    admin:
      client:
        url: http://localhost:9090/admin # Your Admin Server port

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: localhost

# Swagger / OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env"
  endpoint:
    health:
      show-details: always